[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "mkdir -p storage && bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0 -p $PORT"
healthcheckPath = "/up"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
